project:
  type: book
  output-dir: _book

book:
  title: "Experiment Inference Notes"
  chapters:
    - index.qmd
    - href: treatment-group-means/index.qmd
      text: Treatment Group Means
    - href: lift/index.qmd
      text: Relative Treatment Effects
    - href: ratio/index.qmd
      text: Ratio Metrics
    - diagnostics/index.qmd
    - uniform-asymptotics/index.qmd

crossref:
  chapters: false
  ref-hyperlink: true

format:
  html:
    css: styles.css
    toc: false
    number-sections: false